# Generated by Django 3.0.7 on 2020-07-18 11:32

import cloudinary.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Hood',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image', cloudinary.models.CloudinaryField(max_length=255, verbose_name='image')),
                ('residents', models.CharField(max_length=100)),
                ('location_name', models.CharField(choices=[('Westlands', 'Westlands'), ('Parklands', 'Parklands'), ('Kilimani', 'Kilimani'), ('Machakos', 'Machakos'), ('Nakuru', 'Nakuru'), ('Kisumu', 'Kisumu'), ('Bungoma', 'Bungoma'), ('Ruaka', 'Ruaka'), ('Ruiru', 'Ruiru'), ('Kibera', 'Kibera'), ('Kitengela', 'Kitengela'), ('Athi River', 'Athi River'), ('Thika', 'Thika'), ('Syokimau', 'Syokimau'), ('Utawala', 'Utawala'), ('Kasarani', 'Kasarani'), ('Ngong', 'Ngong'), ('Embu', 'Embu'), ('Runda', 'Runda'), ('Voi', 'Voi'), ('Komarock', 'Komarock'), ('Donholm', 'Donholm'), ('Kileleshwa', 'Kileleshwa'), ('Mombasa', 'Mombasa')], max_length=100)),
            ],
            options={
                'ordering': ['-pk'],
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('profile_picture', cloudinary.models.CloudinaryField(max_length=255, verbose_name='image')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('bio', models.CharField(max_length=100)),
                ('full_names', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Resident',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254)),
            ],
            options={
                'ordering': ['first_name'],
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(max_length=300)),
                ('title', models.CharField(max_length=65)),
                ('hood', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='hood.Hood')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Business',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('business_name', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=50)),
                ('category', models.CharField(max_length=30)),
                ('hood', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hood.Hood')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
